# Generated by Django 4.1.2 on 2022-11-07 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('subject', models.CharField(db_column='subject_id', max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('instructor', models.CharField(max_length=200)),
                ('course_number', models.IntegerField(db_column='subj_id', primary_key=True, serialize=False)),
                ('semester_code', models.IntegerField()),
                ('course_section', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('catalog_number', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('units', models.CharField(max_length=200)),
                ('component', models.CharField(max_length=200)),
                ('class_capacity', models.IntegerField()),
                ('wait_list', models.IntegerField()),
                ('wait_cap', models.IntegerField()),
                ('enrollment_total', models.IntegerField()),
                ('enrollment_available', models.IntegerField()),
                ('topic', models.CharField(max_length=200)),
                ('meetings', models.CharField(max_length=200)),
            ],
        ),
    ]
