# Generated by Django 4.1.2 on 2022-11-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('louslist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.IntegerField(primary_key=True, serialize=False)),
                ('course_id', models.CharField(max_length=8)),
                ('overall_rating', models.IntegerField()),
                ('difficulty_rating', models.IntegerField()),
                ('user_email', models.CharField(max_length=50)),
                ('review_title', models.CharField(max_length=200)),
                ('review_text', models.CharField(max_length=600)),
            ],
        ),
    ]
