# Generated by Django 4.1.1 on 2022-11-08 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('louslist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=50)),
                ('userEmail', models.CharField(max_length=50)),
                ('userFriends', models.ManyToManyField(blank=True, to='louslist.uniqueuser')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
