# Generated by Django 4.1.1 on 2022-11-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('louslist', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dept',
            name='id',
        ),
        migrations.AlterField(
            model_name='dept',
            name='subject',
            field=models.CharField(db_column='subject_id', max_length=200, primary_key=True, serialize=False),
        ),
    ]
