# Generated by Django 4.1.1 on 2022-11-06 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('louslist', '0004_remove_dept_id_alter_dept_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('instructor', models.CharField(max_length=200)),
                ('course_number', models.IntegerField(db_column='subj_id', primary_key=True, serialize=False)),
                ('semester_code', models.IntegerField()),
                ('course_section', models.IntegerField()),
                ('subject', models.CharField(max_length=200)),
                ('catalog_number', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('units', models.IntegerField()),
                ('component', models.CharField(max_length=200)),
                ('class_capacity', models.IntegerField()),
                ('wait_list', models.IntegerField()),
                ('wait_cap', models.IntegerField()),
                ('enrollment_total', models.IntegerField()),
                ('enrollment_available', models.IntegerField()),
                ('topic', models.CharField(max_length=200)),
                ('meetings', models.CharField(max_length=200)),
            ],
        ),
    ]
